#!/bin/sh /etc/rc.common

START=50
STOP=10
# USE_PROCD=1

VERYSYNC="/usr/bin/verysync"

start() {
	local enabled="$(uci get verysync.config.enabled)"
	local port="$(uci get verysync.config.port)"
	local profile="$(uci get verysync.config.profile)"
	
	if pgrep -f /usr/bin/verysync >/dev/null; then
		echo '已经有在运行了'
		exit 0
	else
		echo 'starting'
	fi

	[ "${enabled}" == "1" ] || exit 0
	export HOME="/root/"
	
	# /usr/bin/verysync -gui-address=0.0.0.0:8886 -logfile=/var/log/verysync.log -home=/etc/verysync/ -no-browser >/dev/null 2>&1 &
	"${VERYSYNC}" -gui-address="0.0.0.0:${port}" -logfile="/var/log/verysync.log" -home="${profile}" -no-browser >/dev/null 2>&1 &
}

stop() {
	echo 'stoping'
	kill -9 `pgrep "verysync"` >/dev/null 2>&1
}
